# Generated by Django 4.0.6 on 2023-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=128, primary_key=True, serialize=False), max_length=64),
        ),
    ]
